# added static IP 
networks:
  servarr:
    name: servarr
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.0.0/24

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      PUID: "501"
      PGID: "20"
      TZ: Asia/Bangkok
    ports:
      - "8096:8096"
    volumes:
      - "${HOME}/server/jellyfin/config:/config"
      - "${HOME}/server/jellyfin/cache:/cache"
      - "${HOME}/server/media:/media"
    restart: unless-stopped
    networks:
      servarr:
        ipv4_address: 172.40.0.2

  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      TZ: Asia/Bangkok
      PORT: "5055"
    ports:
      - "5055:5055"
    volumes:
      - "${HOME}/server/jellyseerr:/app/config"
    depends_on:
      - jellyfin
    restart: unless-stopped
    networks:
      servarr:
        ipv4_address: 172.40.0.3

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      PUID: "501"
      PGID: "20"
      TZ: Asia/Bangkok
      WEBUI_PORT: "8080"
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - "${HOME}/server/qbittorrent:/config"
      - "${HOME}/server/downloads:/downloads"
    restart: unless-stopped
    networks:
      servarr:
        ipv4_address: 172.40.0.4

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      PUID: "501"
      PGID: "20"
      TZ: Asia/Bangkok
    ports:
      - "8989:8989"
    volumes:
      - "${HOME}/server/sonarr:/config"
      - "${HOME}/server/media/tv:/tv"
      - "${HOME}/server/downloads:/downloads"
    depends_on:
      - qbittorrent
    restart: unless-stopped
    networks:
      servarr:
        ipv4_address: 172.40.0.5

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      PUID: "501"
      PGID: "20"
      TZ: Asia/Bangkok
    ports:
      - "7878:7878"
    volumes:
      - "${HOME}/server/radarr:/config"
      - "${HOME}/server/media/movies:/movies"
      - "${HOME}/server/downloads:/downloads"
    depends_on:
      - qbittorrent
    restart: unless-stopped
    networks:
      servarr:
        ipv4_address: 172.40.0.6

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      PUID: "501"
      PGID: "20"
      TZ: Asia/Bangkok
    ports:
      - "9696:9696"
    volumes:
      - "${HOME}/server/prowlarr:/config"
    restart: unless-stopped
    networks:
      servarr:
        ipv4_address: 172.40.0.7

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      TZ: Asia/Bangkok
      LOG_LEVEL: info
    ports:
      - "8191:8191"
    restart: unless-stopped
    networks:
      servarr:
        ipv4_address: 172.40.0.8

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      PUID: "501"
      PGID: "20"
      TZ: Asia/Bangkok
    ports:
      - "6767:6767"
    volumes:
      - "${HOME}/server/bazarr:/config"
      - "${HOME}/server/media/tv:/tv"
      - "${HOME}/server/media/movies:/movies"
    restart: unless-stopped
    networks:
      servarr:
        ipv4_address: 172.40.0.9
