services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    ports:
      - "8096:8096"
    volumes:
      - "${HOME}/server/jellyfin/config:/config"
      - "${HOME}/server/jellyfin/cache:/cache"
      - "${HOME}/server/media:/media"
    restart: unless-stopped

  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    init: true
    environment:
      TZ: "Asia/Bangkok"
      PORT: "5055"
      LOG_LEVEL: "info"
    ports:
      - "5055:5055"
    volumes:
      - "${HOME}/server/jellyseerr:/app/config"
    restart: unless-stopped
    depends_on:
      - jellyfin

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      PUID: "501"
      PGID: "20"
      TZ: "Asia/Bangkok"
    ports:
      - "7878:7878"
    volumes:
      - "${HOME}/server/radarr:/config"
      - "${HOME}/server/media/movies:/movies"
      - "${HOME}/server/downloads:/downloads"
    restart: unless-stopped
    depends_on:
      - qbittorrent

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      PUID: "501"
      PGID: "20"
      TZ: "Asia/Bangkok"
    ports:
      - "8989:8989"
    volumes:
      - "${HOME}/server/sonarr:/config"
      - "${HOME}/server/media/tv:/tv"
      - "${HOME}/server/downloads:/downloads"
    restart: unless-stopped
    depends_on:
      - qbittorrent

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      PUID: "501"
      PGID: "20"
      TZ: "Asia/Bangkok"
      WEBUI_PORT: "8080"
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - "${HOME}/server/qbittorrent:/config"
      - "${HOME}/server/downloads:/downloads"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: Asia/Bangkok
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: 86400   # once per day
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      PUID: "501"
      PGID: "20"
      TZ: "Asia/Bangkok"
    ports:
      - "9696:9696"
    volumes:
      - "${HOME}/server/prowlarr:/config"
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      LOG_LEVEL: info
      TZ: Asia/Bangkok
    ports:
      - "8191:8191"
    restart: unless-stopped

